export const logoStyles = [
  "Minimalist",
  "Vintage",
  "Modern",
  "Geometric",
  "Pictorial",
  "Abstract",
  "Mascot",
  "Hand-drawn",
  "Watercolor",
  "Neon",
  "Retro",
  "Flat",
  "Art Deco",
  "Luxury",
  "Industrial",
  "Organic",
  "Sporty",
  "Calligraphic",
  "Stencil",
  "Comic",
  "Pixel Art",
  "Mosaic",
  "Brush Stroke",
  "Origami",
  "Line Art",
  "Metallic",
  "Duotone",
  "Tribal",
  "Graffiti",
  "Simplistic",
] as const;

export const logoTypes = [
  "Pictorial Mark",
  "Abstract Logo Mark",
  "Mascot",
] as const;

export const movements = [
  "Abstract Expressionism",
  "Bauhaus",
  "Cubism",
  "Minimalism",
  "Art Deco",
  "Art Nouveau",
  "Pop Art",
  "Surrealism",
  "Futurism",
  "Modernism",
  "Dadaism",
  "Constructivism",
  "Postmodernism",
  "Psychedelic Art",
  "Swiss Design",
] as const;

export const designers = [
  "Paul Rand",
  "Saul Bass",
  "Milton Glaser",
  "Herb Lubalin",
  "Massimo Vignelli",
  "Ivan Chermayeff",
  "Tom Geismar",
  "Alan Fletcher",
  "Wim Crouwel",
  "Michael Bierut",
  "Paula Scher",
  "Stefan Sagmeister",
  "Jessica Walsh",
  "David Carson",
  "Jan Tschichold",
  "Otl Aicher",
  "Josef Müller-Brockmann",
  "Lester Beall",
  "Peter Behrens",
  "Neville Brody",
  "Bradbury Thompson",
  "Peter Saville",
  "Seymour Chwast",
  "Erik Spiekermann",
  "April Greiman",
  "Wolfgang Weingart",
  "Alexey Brodovitch",
  "László Moholy-Nagy",
  "El Lissitzky",
  "Max Bill",
  "Adrian Frutiger",
  "Armin Hofmann",
  "George Lois",
  "Louise Fili",
  "Michael Graves",
  "Raymond Loewy",
  "Dieter Rams",
  "Le Corbusier",
  "Charles and Ray Eames",
  "Zaha Hadid",
  "Tadao Ando",
  "Richard Meier",
  "Mario Botta",
  "Renzo Piano",
  "Frank Gehry",
  "Mies van der Rohe",
  "Walter Gropius",
  "Philippe Starck",
  "Karim Rashid",
  "Ettore Sottsass",
] as const;
